### ISSUE TITLE
内容

### ISSUE THREAD

**Issue by IceSword8492** [IceSword8492/unit-website#2]
各ページの内容(文章)

**Comment by IceSword8492** [comment]
@pridetarou @00547daic @kuma240 

本文まだですか

**Comment by kuma240** [comment]
トップ、ランキング、ダウンロード以外はやっておきました。

**Comment by IceSword8492** [comment]
@kuma240 
# 早急に修正してください

**一旦masterにマージしましたが、問題が多すぎるので戻しておきました**

## 問題点

- ブランチ名が変です

- 画像をルートに置いてはいけません
  
- なぜ項目が一つになっているんですか？
  - あと、ヘッダのタイトルはサイドメニューと意味を合わせてあるので修正してください
https://github.com/IceSword8492/unit-website/blob/4b42df00a4fae168a5d67896583379f318d96302/about.html#L58-L65
  
- 箇条書きなら ul, liタグを使います
https://github.com/IceSword8492/unit-website/blob/4b42df00a4fae168a5d67896583379f318d96302/challenge.html#L58-L62
https://github.com/IceSword8492/unit-website/blob/3a40d198ee50b32fb1c004588875dd962b9be775/hint.html#L59-L65
  
- 謎の記号を削除してください
https://github.com/IceSword8492/unit-website/blob/3a40d198ee50b32fb1c004588875dd962b9be775/feature.html#L58-L67
  
- 意味がわかりません
https://github.com/IceSword8492/unit-website/blob/3a40d198ee50b32fb1c004588875dd962b9be775/screenshots.html#L60

- 最新の画像を使用してください
https://github.com/IceSword8492/unit-website/blob/3a40d198ee50b32fb1c004588875dd962b9be775/screenshots.html#L63

**Comment by kuma240** [comment]
・なぜ項目が一つになっているんですか？
　先週の他のグループの概念項目を見せてもらって、何書くのかも聞いたんだけど、概念項目はあらすじというかストーリーを書いたっていうグループが多かったからそうした方が良いと思って変更した。

**Comment by IceSword8492** [comment]
#4 の決定に反する変更はスタイルの実装に大きな影響を与えるので、ISSUEを立てて相談してからにしてください。

**Comment by kuma240** [comment]
・謎の記号を削除してください
記号があった方が見やすいと思ったんだけど、消した方が良いなら消すよ

**Comment by kuma240** [comment]
・ブランチ名が変です
ブランチ名が変というのは？

**Comment by IceSword8492** [comment]
指示された作業を行ってください。
それぞれの指示への返答は不要です。
実装に関して指示以外の実装をしたい場合はISSUEを立ててください。

**Comment by kuma240** [comment]
@IceSword8492 
とりあえず問題点は最新の画像以外修正したつもり
最新の画像についてはlineのグループに上杉が質問してるからまだ保留で。

**Comment by kuma240** [comment]
@IceSword8492
            <ul>
                <li>敵を倒して知識をしっかり集めること</li>
                <li>スキルをうまく使うこと</li>
                <li>レポート用紙とエナジードリンクを買うためのお金の使い方</li>
                <li>早くクリアして高スコアを目指そう</li>
            </ul>
ってやったのに箇条書きになってなかったんだけど、

**Comment by kuma240** [comment]
@IceSword849

screenshots.htmlのmescore.pngを最新のに修正しておきました。

**Comment by IceSword8492** [comment]
なんでCloseされてるんや

> ってやったのに箇条書きになってなかったんだけど、どうしてかわかる？

スタイル当たってないから

**Comment by IceSword8492** [comment]
# 今後の修正内容

- Aboutの内容が初期と変わってないから加筆

- Featureと特徴の意味がかぶってるから修正

- アピールポイントだけサイズが大きいので修正(特徴と同じ階層にしようとしたのはわかるが上の修正で特徴が消えるので他の文字と同じ大きさに修正)

- 今日中に俺がスタイル当てようと思ったけどもう時間が厳しいからスタイルは自分で当てて(ul, liを箇条にするのと、画像の縦横比をオリジナルの画像と同じサイズにする)

**Comment by 00547daic** [comment]
特徴の文字を削除してアピールポイントを他のものとサイズを同一化しました
aboutの内容は少し加筆しましたが本当に少しです。
ul,liがついてる部分の初めの文字の場所を固定、行間をclassを使って少し調整しました

質問：箇条書きのul,liって書いた時点でデフォルトでdisc(黒ポチ)あるものだと思ったんだけどないからlist-styleでやっても黒ポチでないんだけどどうして？
@IceSword8492

**Comment by pridetarou** [comment]
about 1文加筆してみました

**Comment by kuma240** [comment]
画像の縦横比をオリジナルの画像と同じサイズにしました
