### ISSUE TITLE
概念ページ

### ISSUE THREAD

**Issue by IceSword8492** [IceSword8492/unit-website#4]
@kuma240 

[概念ページ](https://icesword8492.github.io/unit-website/about.html)のレイアウトを以下のようにするのはどうだろうか？

![93d80facb8a26564fc2f7e5df1e00e2d](https://user-images.githubusercontent.com/28210998/61577672-ac0a3300-ab25-11e9-9e4f-3d676a1abea9.png)

**Comment by kuma240** [comment]
ありだと思う。見栄え良くなるけど、俺そのやり方分からないんだけど。

2019年7月20日(土) 午後7:38 Sharo <notifications@github.com>:

**Comment by IceSword8492** [comment]
見た目は俺が編集してもいいからとりあえず文めっちゃ長くしといちくり～

**Comment by kuma240** [comment]
最終版のWebページって、こっちのともう一つの吉岡・上杉が作ったWebサイトと合わせるみたいな感じでいいのかな？

**Comment by IceSword8492** [comment]
合わせるの意味がわからんけどとりあえず早く実装してください。

**Comment by IceSword8492** [comment]
#2 に移行
