### ISSUE TITLE
現在内容の問題を修正しています

### ISSUE THREAD

**Issue by kuma240** [IceSword8492/unit-website#7]

**Comment by kuma240** [comment]
・修正ができていないところ
箇条書きにした方が良いところが、<ul>、<li>タグを使っているのに箇条書きになっていない

**Comment by kuma240** [comment]
@IceSword8492  @pridetarou  @00547daic 
この原因が分からないので、皆さんでお願いします。

**Comment by IceSword8492** [comment]
#2
